package database;

import java.sql.ResultSet;

public class DBUtil {
	public static int getAutoGeneratedKeyFromResultSet(ResultSet resultSet,int index){
		try{
			if(resultSet.first()){
				return resultSet.getInt(index);
			}
		}
		catch(Exception e){
			
		}
		return -1;
	}
	
	public static int getAutoGeneratedKeyFromResultSet(ResultSet resultSet){
		return getAutoGeneratedKeyFromResultSet(resultSet,1);
	}
}
